version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: todoUser
      MONGO_INITDB_ROOT_PASSWORD: Todod2019*
      MONGO_INITDB_DATABASE: todo
